language: python
sudo: false
env:
  global:
    secure: "OwcNfLq3nPhDkIwLA2In6YFB1+o9/J5vzHEUxCD0KNRrA1XTKbF1qWJcetUY4bTI/TUdMTTLU1WJ9BTIJVkivmLGzgmjluCyC0kaXe7+qZLQnoLjUM4wBpoT53bZ8XTCJQ7gKwQ8CyPK7EEDyINKUgHtPrDVMyoee9EsBH4sJWA="

python:
  - 3.5

script:
  - if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
      gem install travis;
      echo "y" | travis login --github-token $GH_TOKEN;
      python restart_travis.py;
    fi;